### ISSUE TITLE
"Rounds" page doesn't display runners

### ISSUE THREAD

**Issue by Goosly** [coder13/Competitor-groups#7]
The "rounds" page (not sure what to call it) displays Compete, Judge, Scramble assignments, but is missing runners.

Example:
https://www.competitiongroups.com/competitions/BruggeOpen2023/events/333-r1

The first competitor, Aden, competes in 6 and runs in 2. The latter is not shown.

It is shown correctly on the "Person" page: https://www.competitiongroups.com/competitions/BruggeOpen2023/persons/157
And also correctly on the "Group" page: https://www.competitiongroups.com/competitions/BruggeOpen2023/activities/34

**Comment by coder13** [comment]
Honestly this page needs a huge overhaul. I've never been a fan of it.
